name: 'Setup Python + Poetry environment'
description: 'Setup Python + Poetry environment'

inputs:
  python-version:
    required: false
    description: 'Python version'
    default: '3.9'
outputs: {}
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{inputs.python-version}}
    - name: Install poetry
      run: python -m pip install poetry
      shell: bash
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
    - if: ${{ steps.cached-poetry-dependencies.outputs.cache-hit != 'true' }}
      name: Create virtual environment
      run: poetry install
      shell: bash
